[tools]

fastfetch = "latest"
jq = "latest"
fzf = "latest"

bun = "latest"
node = "latest"
go = "latest"
java = "openjdk-24"
python = "latest"
ruby = "latest"

gh = "latest"
pipx = "latest"
aws-cli = "latest"
aws-sam-cli = "latest"
cfn-lint = "latest"
terraform = "latest"
